# Generated by Django 5.0.6 on 2024-06-02 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_basketproduct_name_alter_basketproduct_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="basketproduct",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.basket",
            ),
        ),
        migrations.CreateModel(
            name="PaymentInformationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_address", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=10)),
                ("credit_card_number", models.CharField(max_length=16)),
                ("expiration_date", models.DateField()),
                ("security_code", models.CharField(max_length=3)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
