# Generated by Django 5.0.6 on 2024-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_address_alter_basketproduct_basket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketproduct",
            name="store_product_id",
            field=models.IntegerField(default=0),
        ),
    ]
