# Generated by Django 5.0.6 on 2024-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_basketproduct_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketproduct",
            name="category",
            field=models.CharField(default="category", max_length=100),
        ),
    ]
